
project_id = "khkytmxfrbtcwppmehkd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
# Uncomment to expose additional ports
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://khkytmxfrbtcwppmehkd.supabase.co"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.validate-app-store-receipt]
verify_jwt = false

[functions.app-store-webhook]
verify_jwt = false

[functions.check-feature-access]
verify_jwt = true

[functions.check-subscription-config]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
inspector_port = 8083
