// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khkytmxfrbtcwppmehkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtoa3l0bXhmcmJ0Y3dwcG1laGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzg4NDAsImV4cCI6MjA2MjkxNDg0MH0.HgMLChsoJ1yu3fVU7PpfN8mu_X6g98w7JclxFVP7Ipo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);